#ifndef __BSP_LED_H
#define __BSP_LED_H

#define RED_LED_GPIO_PORT 		GPIOA
#define RED_LED_GPIO_CLK 			RCC_APB2Periph_GPIOA
#define RED_LED_GPIO_PIN 			GPIO_Pin_11
#define RED_LED_ON 						GPIO_SetBits(RED_LED_GPIO_PORT, RED_LED_GPIO_PIN)
#define RED_LED_OFF 					GPIO_ResetBits(RED_LED_GPIO_PORT, RED_LED_GPIO_PIN)

#define YELLOW_LED_GPIO_PORT 	GPIOA
#define YELLOW_LED_GPIO_CLK 		RCC_APB2Periph_GPIOA
#define YELLOW_LED_GPIO_PIN 		GPIO_Pin_12
#define YELLOW_LED_ON 					GPIO_SetBits(YELLOW_LED_GPIO_PORT, YELLOW_LED_GPIO_PIN)
#define YELLOW_LED_OFF 					GPIO_ResetBits(YELLOW_LED_GPIO_PORT, YELLOW_LED_GPIO_PIN)

#define GREEN_LED_GPIO_PORT 		GPIOB
#define GREEN_LED_GPIO_CLK 			RCC_APB2Periph_GPIOB
#define GREEN_LED_GPIO_PIN 			GPIO_Pin_5
#define GREEN_LED_ON 					GPIO_SetBits(GREEN_LED_GPIO_PORT, GREEN_LED_GPIO_PIN)
#define GREEN_LED_OFF 					GPIO_ResetBits(GREEN_LED_GPIO_PORT, GREEN_LED_GPIO_PIN)


void RED_LED_GPIO_Config(void);
void YELLOW_LED_GPIO_Config(void);
void GREEN_LED_GPIO_Config(void);
void LED_GPIO_Config(void);

#endif